version: '3'
services:  
  redis:
    container_name: basic-redis-chat
    image: redis    
    restart: always
    command: redis-server --appendonly yes --requirepass 123456    
    ports:
      - "6379:6379"
